server:
    port: ${SERVER_PORT}
    servlet:
        context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:
    profiles:
        active: dev
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    batch_size: 1000
                order_inserts: true
                order_updates: true
    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}
        database: ${REDIS_DATABASE}
        timeout: 2000
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

jwt:
    signerKey: ${JWT_SIGNERKEY}
    accessToken:
        expirationTime: 900
    refreshToken:
        expirationTime: 2592000

vnpay:
    tmnCode: ${VNPAY_TMN_CODE}
    secretKey: ${VNPAY_SECRET_KEY}
    payUrl: ${VNPAY_PAY_URL}
    returnUrl: ${VNPAY_RETURN_URL}
    command: ${VNPAY_COMMAND}
    version: ${VNPAY_VERSION}

app:
    cors:
        allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}